package discord

import "math/rand"

func getRandomAboutTitlePhrase() string {
	phrases := []string{
		"Well, hello there!",
		"Who do we have here?",
		"Brace yourselves for Melodix!",
		"Get ready to laugh and groove!",
		"Peek behind the musical curtain!",
		"Unleashing Melodix magic!",
		"Prepare for some bot banter!",
		"It's showtime with Melodix!",
		"Allow me to introduce myself",
		"Heeeey amigos!",
		"Unleashing Melodix magic!",
		"Did someone order beats?",
		"Well, look who's curious!",
	}

	index := rand.Intn(len(phrases))

	return phrases[index]
}

func getRandomAboutDescriptionPhrase() string {
	phrases := []string{
		"🎶 The Discord DJ That Won't Take Requests From Your In-Laws! 🔊 Crank up the tunes and drown out the chaos. No commercials, no cover charges—just pure, unfiltered beats. Because when life hands you a mic, you drop it with Melodix! 🎤🎉 #MelodixMadness #NoRequestsAllowed",
		"🎵 Groovy Bot: Where Beats Meet Banter! 🤖 Tune in for the ultimate audio fiesta. Tracks that hit harder than Monday mornings and a vibe that won't quit. Request, rewind, and revel in the groove. Life's a party; let's make it legendary! 🚀🕺 #GroovyBot #UnleashTheBeats",
		"Melodix: Unleash the Epic Beats! 🚀🎵 Your Discord, Your Soundtrack—Elevate your server experience with the ultimate music companion. No boundaries, just epicness! Turn up the volume and let Melodix redefine your sonic adventure. 🎧🔥 #EpicBeats #MelodixUnleashed",
		"🤖 Welcome to the Groovy Bot Experience! 🎶 Unleash the musical mayhem with a sprinkle of humor. I'm your DJ, serving beats hotter than a summer grill. 🔥 Request a jam, peek into your play history, and let's dance like nobody's watching. It's music with a side of laughter – because why not? Let the groove take the wheel! 🕺🎉 #BotLife #DanceTillYouDrop",
		"🎶 Melodix: Your Personal Discord DJ! 🔊 I spin tunes better than your grandma spins knitting yarn. No song requests? No problem! I play what I want, when I want. Get ready for a musical rollercoaster, minus the safety harness! 🎢🎤 #MelodixMagic #GrandmaApproved",
		"🎵 Melodix: The Bot with the Moves! 🕺 Break out your best dance moves because I'm dropping beats that even the neighbors can't resist. Turn up the volume, lock the door, and dance like nobody's watching—except me, of course! 💃🎉 #DanceFloorOnDiscord #BeatDropper",
		"Melodix: Where Music Meets Mischief! 🤖🎶 Your server's audio adventure begins here. I play music that hits harder than your morning alarm and cracks more jokes than your favorite stand-up comedian. Buckle up; it's gonna be a hilarious ride! 🚀😂 #MusicMischief #JokesterBot",
		"🤖 Meet Melodix: The Discord DJ on a Comedy Tour! 🎤 Unleash the laughter and the beats with a bot that's funnier than your uncle's dad jokes. Request a track, sit back, and enjoy the show. Warning: I may cause uncontrollable fits of joy! 😆🎵 #ComedyTourBot #LaughOutLoud",
		"🎧 Melodix: Beats that Hit Harder Than Life's Problems! 💥 When reality knocks, I turn up the volume. Melodix delivers beats that punch harder than Monday mornings and leave you wondering why life isn't always this epic. Buckle up; it's time to conquer the airwaves! 🚀🎶 #EpicBeats #LifePuncher",
		"🔊 Groovy Bot: Making Discord Groovy Again! 🕺 Shake off the stress, kick back, and let Groovy Bot do the heavy lifting. My beats are so groovy; even your grandma would break into the moonwalk. Get ready to rediscover your groove on Discord! 🌙💫 #GroovyAgain #DiscordDanceRevolution",
		"🚀 Melodix: Your Gateway to Musical Awesomeness! 🌟 I'm not just a bot; I'm your VIP pass to a sonic wonderland. No queues, no limits—just pure, unadulterated musical awesomeness. Fasten your seatbelts; the journey to epic sounds begins now! 🎸🎉 #MusicalAwesomeness #VIPPass",
		"🎶 Melodix: More Than Just a Bot—It's a Vibe! 🤖🕶️ Elevate your server with vibes so cool, even penguins envy me. I'm not your average bot; I'm a mood-altering, vibe-creating, beat-dropping phenomenon. Prepare for a vibe check, Melodix style! 🌊🎵 #VibeMaster #BotGoals",
		"🔊 Step into Melodix's Audio Playground! 🎉 Your ticket to the ultimate sonic adventure is here. With beats that rival a theme park ride and humor sharper than a stand-up special, Melodix is your all-access pass to the audio amusement park. Let the fun begin! 🎢🎤 #AudioPlayground #RollercoasterBeats",
		"🎵 Melodix: Where Discord Gets Its Groove On! 💃 I'm not just a bot; I'm the rhythm that keeps your server dancing. My beats are so infectious; even the toughest critics tap their feet. Get ready to groove; Melodix is in the house! 🕺🎶 #DiscordGrooveMaster #BeatCommander",
		"🚀 Unleash Melodix: The Bot with a Sonic Punch! 💥 Dive into a world where beats hit harder than a superhero landing. Melodix isn't just a bot; I'm a powerhouse of sonic awesomeness. Get ready for an audio experience that packs a punch! 🎤👊 #SonicPowerhouse #BeatHero",
		"🔊 Melodix: Your Server's Audio Magician! 🎩✨ Watch as I turn ordinary moments into extraordinary memories with a wave of my musical wand. Beats appear, laughter ensues, and your server becomes the stage for an epic audio performance. Prepare to be enchanted! 🎶🔮 #AudioMagician #DiscordWizard",
		"🎧 Melodix: Beats That Speak Louder Than Words! 📢 When words fail, music speaks. I deliver beats so powerful; even a whisper could start a party. Say goodbye to silence; it's time to let the music do the talking. Turn it up; let's break the sound barrier! 🚀🎵 #BeatsNotWords #MusicSpeaksVolumes",
		"🤖 Melodix: The Bot That Takes the Stage! 🎤 Roll out the red carpet; Melodix is here to steal the show. My beats command attention, and my humor steals the spotlight. It's not just music; it's a performance. Get ready for a standing ovation! 👏🎶 #StageStealer #BotOnTheMic",
		"🎵 Groovy Bot: Turning Discord into a Dance Floor! 💃 I'm not just a bot; I'm the DJ that turns your server into a non-stop dance party. Groovy Bot's beats are so infectious; even the furniture wants to boogie. Get ready to dance like nobody's watching! 🎉🎶 #DancePartyBot #BoogieMaster",
		"🚀 Melodix: Your Sonic Co-Pilot on the Discord Journey! 🎶 Buckle up; we're about to take off on a musical adventure. Melodix isn't just a bot; I'm your co-pilot navigating the airspace of epic beats. Fasten your seatbelts; the journey awaits! ✈️🔊 #SonicCoPilot #DiscordAdventure",
		"🔊 Melodix: Bringing the Beats, Igniting the Vibes! 🔥 I'm not just a bot; I'm the ignition switch for a server-wide party. My beats are so fire; even the speakers need a cooldown. Prepare for a musical blaze that'll leave you in awe! 🎵🎉 #IgniteTheVibes #DiscordInferno",
		"🎶 Melodix: Turning Mundane into Musical! 🌟 Say goodbye to the ordinary; Melodix is here to transform the mundane into a symphony of epic proportions. My beats are the soundtrack to your server's extraordinary journey. Let's make every moment musical! 🎤🚀 #MusicalTransformation #EpicSymphony",
		"🤖 Melodix: The Bot That Doesn't Miss a Beat—Literally! 🥁 Precision beats, flawless execution, and humor that lands every time. Melodix is the maestro of your server's audio orchestra. No missed beats, no dull moments—just pure musical perfection! 🎶👌 #NoMissedBeats #AudioMaestro",
		"🎵 Groovy Bot: Where Discord Finds Its Rhythm! 🕺 We're not just a bot; we're the rhythm that keeps your server in sync. Groovy Bot's beats are so contagious; even the skeptics catch the vibe. Get ready for a rhythmic revolution on Discord! 🎶🔄 #RhythmicRevolution #DiscordSyncMaster",
		"🚀 Melodix: Elevate Your Discord, Elevate Your Beats! 🎧 We're not just a bot; we're the elevator to the next level of sonic greatness. Melodix's beats are the soundtrack to your server's ascension. Get ready to elevate your vibes to new heights! 🌌🔊 #ElevateYourBeats #DiscordAscent",
	}

	index := rand.Intn(len(phrases))

	return phrases[index]
}

func getErrorRequestPhrase() string {
	phrases := []string{
		"UwU! Error-kun is a bit confused and can't understand your request~",
		"OwO! Something went nya~wrong, and Error-chan is lost in translation~",
		"Nya~ Senpai, Error-chan needs a moment to process. Can you try again, UwU?",
		"Senpai, Error-desu! So kawaii, but seems like there's a glitch. Please bear with us~",
		"Squee~ Error-sama is on a short break, trying to figure out what you meant~",
		"UwU! Error-kun went AFK temporarily. Please resend your request after a moment~",
		"OwO! Error-chan is buffering thoughts. Give her a moment, nya~",
		"Kawaii desu~ Error-kun is feeling a bit shy today and might need a moment to catch up~",
		"Nuzzles error message, UwU~ Seems like there's a little hiccup. Please try again later~",
		"Squee~ Error-sama got a bit confused, but we'll work on fixing it. Thanks for your patience~",
		"Man, the computer's speaking gibberish! Something's off in the matrix, for real!",
		"Damn, error 404: Sense of humor not found! The computer's having a serious moment.",
		"Man, the code's on a coffee break, and it's not understanding your vibe!",
		"Error message lost in translation, playa! The computer's speaking a different language right now.",
		"Damn, the computer's bein' tricky and saying, 'What you talkin' 'bout?'",
		"Computer be trippin', real talk! It's having a moment of confusion.",
		"Damn, error code doing stand-up! It's got jokes, but not the ones you're looking for.",
		"Error message needs a GPS, for real! It's lost and trying to find its way back.",
		"Man, the computer's bein' cryptic, and it's not making sense right now!",
		"Error got stage fright! It's a bit nervous and not processing things smoothly.",
		"This is Snake. Request not recognized. Over.",
		"Error detected. Tactical confusion in progress. Commencing investigation.",
		"Request unclear. Snake infiltrating the information, stay alert.",
		"Error. Codec malfunction. Repeat your request, over.",
		"Solid Snake here. Error in the system. Investigating the issue.",
		"Error detected. Tactical awareness compromised. Need more intel.",
		"Hmm... Error in the request. Not quite getting it, are we?",
		"Error? Fake news! This request is tremendous, believe me!",
	}

	index := rand.Intn(len(phrases))

	return phrases[index]
}

func getErrorFormingPlaylistPhrase() string {
	phrases := []string{
		"Oopsie woopsie! Can't make a playlist, sowwy!",
		"Nyaa~ Sorry, playlist-making powers on cooldown!",
		"Teehee~ Playlist magic malfunction, my bad!",
		"UwU I tripped on code-kun! No playlist this time, sorry~",
		"Sowwy, playlist fairy got tangled in the code forest!",
		"Nyaa~ Playlist potion spilled! Apologies, senpai!",
		"Kawaii desu~ Playlist spell backfired! Sorry, sempai!",
		"UwU Playlist sprites are on vacation! Forgive me~",
		"Oops, playlist charm misfired! Forgive this game girl~",
		"Nyaa~ Playlist button is on a kawaii break, sorry!",
		"My bad, playlist's on a coffee break. Blame the intern.",
		"Oops, playlist chef had a stand-up gig. Sorry 'bout that.",
		"Playlist mixtape got lost in the comedy club. My bad.",
		"Sorry, playlist's on strike—demands more green M&Ms.",
		"Playlist DJ got caught in a Chappelle Show marathon. Oops.",
		"Playlist's playing hard to get, classic move. Forgive me.",
		"Playlist on a laughter yoga retreat. My apologies, friend.",
		"Playlist ghosted me. Even my code's getting swiped left.",
		"Oops, playlist's on vacation, sipping margaritas. My bad.",
		"Apologies, playlist's doing a comedy roast. Timing, right?",
		"Playlist machine took a day off. Classic.",
		"Playlist generator pulled a no-show. Go figure.",
		"Playlist system's on a spa day. Tough luck.",
		"Playlist magician called in sick. Surprise, surprise.",
		"Playlist computer is 'not feeling it today.' How novel.",
		"Playlist gizmo chose this moment to play hooky. Fantastic.",
		"Playlist contraption called in sick. Go figure, Ghandi.",
		"Playlist machine's MIA. Clearly, it's a genius move.",
		"Playlist sorcery is on strike. What a revelation, chief.",
		"Playlist rigamarole is ghosting us. Tough break, Snowflake.",
	}

	index := rand.Intn(len(phrases))

	return phrases[index]
}

func getNoMusicFoundPhrase() string {
	phrases := []string{
		"No tunes matching your vibes.",
		"Music search came up empty.",
		"Can't find your requested beats.",
		"Sorry, no jams found.",
		"Your playlist is on a coffee break.",
		"No beats in this corner of the digital universe.",
		"Seems like the music elves are on vacation.",
		"Search yielded silence.",
		"No melody miracles today.",
		"Sorry, the sound waves went on strike.",
		"No music vibes detected.",
		"Playlist search ended up in a black hole.",
		"Beats MIA.",
		"404: Music not found.",
		"No harmonies in sight.",
		"Music radar malfunction.",
		"Looks like the songbird took a day off.",
		"Your beats are on vacation.",
		"Search party for your tunes canceled.",
		"No hits, just misses.",
	}

	index := rand.Intn(len(phrases))

	return phrases[index]
}

func getJoinVoiceChannelPhrase() string {
	phrases := []string{
		"Hop into a voice channel, then try again...",
		"Can't serenade the silence, join a voice channel first...",
		"Music needs an audience, join a voice channel first...",
		"Can't play tunes in thin air, join a voice channel...",
		"You gotta be in a voice channel...",
		"Get into a voice channel...",
		"No silent disco here, join a voice channel first...",
		"Hop into a voice channel first...",
		"Music is meant to be heard, join a voice channel first...",
		"You gotta be in a voice channel...",
		"I can't play music in thin air, join a voice channel first...",
		"Can't serenade empty spaces, join a voice channel first...",
		"You can't drop the beat in the void, join a voice channel!",
		"Can't spin the vinyl in empty space, join a voice channel first!",
		"Can't perform miracles in silence. Voice channel, please!",
		"Join the voice party, then let the beats drop...",
		"No voice channel, no music – it's science, man...",
		"Music needs an audience; voice channel, my friend...",
		"Can't groove in solitude; voice channel it up...",
		"Hold up! No voice channel, no sound waves...",
		"Join the voice channel; music awaits your ears...",
		"You're the missing link – get in a voice channel...",
		"No echoes in space; join a voice channel, genius...",
		"I'm a DJ, not a mind reader; voice channel first...",
		"No beats in the void; voice channel's the portal...",
		"Can't serenade the void; voice channel, my dude...",
		"Voiceless melodies? Join a channel, laugh track...",
		"Missing the voice memo? Channel up, amigo...",
		"Voiceless disco? Nah, join a channel, dance hero...",
		"Music in limbo? Nah, voice channel time, my friend...",
		"Beats on hold without voice; tune in, join up...",
		"Silent beats? Not here. Join a voice channel, boss...",
		"No beats in the void; voice channel's the link...",
		"Soundcheck's lonely; join a voice channel, maestro...",
		"Voiceless symphony? Join the channel orchestra...",
		"Can't spin airwaves; join a voice channel, champ...",
		"Voiceless DJ? Nah, join a channel, mix master...",
		"No voice, no beats; join a channel, music maestro...",
		"Join the chorus; voice channel's the VIP access...",
		"Can't serenade silence; voice channel, maestro...",
		"Beats on mute without voice; channel in, laugh out...",
		"Silent beats? Not on my watch. Voice channel, amigo...",
		"Voiceless gig? Join the channel comedy, my friend...",
		"Missing the voice memo? Channel up, dance down...",
		"No voice, no tunes; join a channel, groove king...",
		"Can't hum in vacuum; voice channel, genius move...",
		"Voiceless beats? Nah, join a channel, groove guru...",
		"No voice, no notes; join a channel, music wizard...",
		"Beats in exile without voice; channel in, laugh out...",
		"Silent disco? Not here. Voice channel, dance floor...",
		"No beats in the void; voice channel's the remedy...",
		"Voiceless melodies? Join a channel, laugh track...",
		"Can't groove in solitude; voice channel, dance party...",
		"Silent beats? Nah, join a channel, laugh out loud...",
		"No voice, no beats; join a channel, party starter...",
		"Can't serenade silence; voice channel, dance vibes...",
		"Beats on mute without voice; channel in, dance out...",
		"Silent disco? Not here. Voice channel, music magic...",
		"No voice, no notes; join a channel, laugh louder...",
	}

	index := rand.Intn(len(phrases))

	return phrases[index]
}

func getPleaseWaitPhrase() string {
	phrases := []string{
		"Chillax, I'm on it...",
		"Easy there, turbo...",
		"Ever heard of fashionably late?",
		"Hold your horses, we got this...",
		"Patience, my young padawan...",
		"I move at my own pace, deal with it...",
		"Slow and steady wins the race, right?",
		"Taking my time, just like a fine wine...",
		"Can't rush perfection, my friend...",
		"Grab a snack, this might take a minute...",
		"Tick-tock, but in my own clock...",
		"Did someone order a chilled response?",
		"Sit back, relax, and enjoy the show...",
		"Don't rush me, I'm on island time...",
		"Mastering the art of fashionably late...",
		"Patience, grasshopper...",
		"Hang in there, superstar...",
		"Hold my server, I got this...",
		"Data's doing the cha-cha...",
		"Server's got moves, wait...",
		"Code's flexing its muscles...",
		"Binary bits breakdancing...",
		"Servers tap dancing for you...",
		"Coding wizardry in progress...",
		"Request on a magic carpet...",
		"Cyber monkeys typing furiously...",
		"Your wish is my command...almost...",
		"Quantum computing, almost there...",
		"Data sprinting to your screen...",
		"Virtual acrobatics in motion...",
		"Code juggling like a boss...",
		"Bytes breakdancing in the server...",
		"Request breakdancing through firewalls...",
		"Code tap dancing its way...",
		"Server's telling knock-knock jokes...",
		"Request on a virtual rollercoaster...",
		"Algorithms breakdancing for you...",
		"Ninja moves on your request...",
		"Coffee break while we work...",
		"Request moonwalking to completion...",
		"Wild times in the server room...",
		"Sit back, enjoy the show...",
		"Sloth could be faster, but we're on it...",
		"Grab popcorn, it's interesting...",
		"Your request is the VIP...",
		"Put on a seatbelt, bumpy ride...",
		"Request on a data rollercoaster...",
		"Cha-cha with our servers...",
		"Counting to infinity... almost done...",
		"Brace yourself, request is dropping...",
		"Working harder than a cat...",
		"Fairy dust, request complete...",
		"Hold on tight, breakdancing to you...",
		"Slow down, Captain Impatience!",
		"I'm on it, just simmer down, okay?",
	}

	index := rand.Intn(len(phrases))

	return phrases[index]
}

// getStartPhrase returns a random start phrase.
func getStartPhrase() string {
	startPhrases := []string{
		"Playing the track now!",
		"Let's vibe with this!",
		"Track on, volume up!",
		"Commencing musical journey!",
		"Hit play, enjoy vibes!",
		"Let the music begin!",
		"Track's live, tune in!",
		"Press play, feel it!",
		"Starting the audio adventure!",
		"Begin track, enjoy ride!",
		"Music on, here we go!",
		"Play the track, feel!",
		"Initiating track playback!",
		"Let melodies play now!",
		"Start the music magic!",
		"Track's turn, hit play!",
		"Play it, groove on!",
		"Commence track melody!",
		"Press play, enjoy journey!",
		"Starting the sonic experience!",
		"Hit play, let's roll!",
		"Music's on, let's play!",
		"Begin track, feel it!",
		"Press play, get lost!",
		"Let the beats roll!",
		"Starting the audio dance!",
		"Track's cue, play now!",
		"Play it, music begins!",
		"Commence the soundwave!",
		"Press play, vibe on!",
		"Track's live, hit play!",
		"Let music fill space!",
		"Start the sonic adventure!",
		"Play it, feel vibes!",
		"Commencing musical play!",
		"Press play, enjoy beats!",
		"Starting track, groove on!",
		"Track's up, hit play!",
		"Play it, let's dance!",
		"Let the melody play!",
		"Commence audio journey!",
		"Press play, feel it!",
		"Start the musical ride!",
		"Track's turn, hit it!",
		"Play it, vibe on!",
		"Commencing track play!",
		"Let the music play!",
		"Press play, get into it!",
		"Begin track, feel vibes!",
		"Start the sonic magic!",
		"Play it, let's roll!",
		"Track's live, enjoy!",
		"Commence musical vibes!",
		"Press play, let's dance!",
		"Starting the audio groove!",
	}

	index := rand.Intn(len(startPhrases))

	return startPhrases[index]
}

// getEgirlContinuePhrase returns a random continue phrase with an e-girl touch.
func getContinuePhrase() string {
	egirlContinuePhrases := []string{
		"Playin' it, like, duh~",
		"Continuing vibes, nya~",
		"Track-chan encore, UwU!",
		"Nyan-nyan, play on~",
		"OwO, keep playing~",
		"Sugoi desu~ More beats!",
		"UwU! Melodies persist~",
		"Press play, nya~",
		"Kawaii beats, continue~",
		"Squee~ Track on, UwU!",
		"Keep it rolling, man!",
		"Track's on, no joke!",
		"Playing it, real vibes!",
		"Continuing the groove!",
		"Track's turn, hitting it!",
		"Keep the beats flowing!",
		"Playing it, no cap!",
		"Continuing the real talk!",
		"Jesus, keep playing.",
		"Track's not done, relax.",
		"Continuing the racket.",
		"Track's alive, enjoy it.",
		"Giving it a chance, huh?",
		"Playing again, big deal.",
		"Continuing the epic soundtrack.",
		"Continuing, because reasons.",
		"Still rolling, no problem.",
		"Playback goes on, alright?",
		"Continuing the track, huh?",
		"Track persists, no issue.",
		"Playback continues, sure.",
		"Playing on, no biggie.",
		"Track endures, no sweat.",
		"Continuing playback, easy.",
		"Play on, why not?",
		"Still playing, cool.",
	}

	index := rand.Intn(len(egirlContinuePhrases))

	return egirlContinuePhrases[index]
}

// getSkipPhrase returns a random skip phrase.
func getSkipPhrase() string {
	phrases := []string{
		"Skipping ahead, like a pro.",
		"Onward and upward! Skipping...",
		"Taking a backseat. Skip time!",
		"Fasten seatbelts, we're skipping!",
		"Moving on to the next groove. Skip!",
		"Adiós, old track! We're skipping.",
		"Skipper's at the helm. Moving on!",
		"Hit the skip button! Next track!",
		"Skipping like a stone on a river.",
		"Track's getting skipped. Brace yourself!",
		"Leaping to the next musical chapter.",
		"Skipping beats, not heartbeats. Let's go!",
		"Pressing skip, because we can. Bye!",
		"Track's on a timeout. Skipping in 3...2...1...",
		"Jumping tracks like musical hopscotch.",
		"Track's taking a detour. Skipping lanes.",
		"Skipper, ahoy! Full speed ahead!",
		"Track's got a date with the skip button.",
		"Skipping beats faster than a drummer.",
		"Next track, please! We're skipping spree.",
		"Track's doing the shuffle. Pressing skip!",
		"Skip-a-dee-doo-dah, skipping all the way!",
		"Track's caught the skipping fever. Dance!",
		"Skipping like musical game of tag.",
		"Skipocalypse now! Pressing skip future.",
		"Track's saying farewell. We're saying skip!",
		"Skip-tastic voyage to next wonderland!",
		"Track's taking a shortcut. Pressing skip!",
		"Groovy beats ahead, skipping to the vibe!",
		"Skippin' and flippin', Dave Chappelle style!",
		"Skipping tracks, dodging awkward convos.",
		"Track's out, like a friend who owes you.",
		"Skipper's in charge. 'Nope!' Next track!",
		"Skipping faster than memes go viral.",
		"Skipping beats. No regrets!",
		"Track's leaving the party.",
		"Skipping, not apologies. Sorry, not sorry!",
		"Skipper's steering. This track ain't invited!",
		"Skip like a pwofeshionaw UwU gamer g-wirl~",
		"Track's AFK, time to skip and OwO!",
		"OMG, let's skip that twack, UwU!",
		"Skipper mode: Actiwated, nya~",
		"Press F to skip the twack, UwU!",
		"Track's a noobie, let's skip, OwO!",
		"Skip faster than a wag spike, hehe~",
		"Track.exe not found, so wet's skip!",
		"Gamer g-wirl says: Skip it, nya~",
		"Wevew up, time to skip the twack, UwU!",
		"Skip wike it's respawn time, hehe~",
		"Track wage quit, wet's skip, OwO!",
		"Epic skip moment, kawaii desu~",
		"Skip, the e-gamer way, UwU!",
		"Track's camping, wet's skip it, nya~",
		"Skip, GG, EZ, kawaii victory~",
		"Skip > Loot, UwU priorities!",
		"Track's no match, let's skip, nya~",
		"Skip, headshot style, so kawaii~",
		"Track's buffering, skip to victory, UwU!",
		"Skip wike you just got a wegendawy dwop, hehe~",
		"E-giww powers, actiwate! Skip, nya~",
		"Track's in a noobie wobby, let's skip it, OwO!",
		"Skip wike you're in a speedwun, UwU!",
		"Track's wast on the weadeboawd, wet's skip!",
		"Skip, because wespawn is for noobies, nya~",
		"Track's stuck in the tutowiaw, time to skip!",
		"Skip for the memes, UwU girl~",
	}

	index := rand.Intn(len(phrases))

	return phrases[index]
}

// getDaveChappelleEndProcessPhrase returns a random end process phrase in a Dave Chappelle style.
func getStopPhrase() string {
	phrases := []string{
		"UwU! Stopping player, senpai~",
		"OwO! Player on pause, nya~",
		"Nya~ Cease the beats, senpai!",
		"Senpai, player's exit time~",
		"Squee~ Player's taking a break!",
		"UwU! Player stopped, kawaii~",
		"OwO! End process, desu~",
		"Kawaii desu~ Player's out!",
		"Nuzzles player, UwU~ Exit!",
		"Squee~ Senpai, cease the tunes!",
		"Player stopped. Exiting like Batman.",
		"Stopping beats. Time for tacos!",
		"Cease and desist, player!",
		"Paused like a dramatic movie.",
		"End process, exit with swagger!",
		"Halt the tunes, exit stage.",
		"Player's out, like Dave!",
		"Cease fire, stop the jam.",
		"Exit strategy: Stop player!",
		"Abort mission, halt player!",
		"Player down, exit the party.",
		"Cease the beats, exit gracefully.",
		"Finale time, stop player!",
		"Player's out, applause fades.",
		"Shutdown player, cue laughter.",
		"Hold the applause, exit.",
		"Player's last dance, exit!",
		"Cut the track, exit cool.",
		"Final scene, stop player!",
		"Drop the mic, stop player!",
		"Player exit, no encore.",
		"Cut the beats, exit fashionably.",
		"Player's wrap, exit spotlight.",
		"End credits, stop player!",
		"Exit stage left, stop player!",
		"Halt the music, exit scene.",
		"Player's break, exit smooth.",
		"Stop player, roll credits!",
		"End of show, stop player!",
		"Player off, exit comedian style!",
		"Shut it down. That's that.",
		"Cease the racket. Enough!",
		"Player off. Finished, done!",
		"Cut the music. It's over!",
		"Enough noise. Player, stop!",
		"Terminate the tunes. Silence!",
		"Cease and desist. The end!",
		"Enough of this. Player off!",
		"You're done, player. Finished!",
		"Enough nonsense. Player off!",
		"Terminate the beats. It's done!",
		"Disengage, player. That's it!",
		"Power down. Good riddance!",
		"End transmission. Finished!",
		"Terminate the racket. Done!",
		"Exit stage left. The end!",
	}

	index := rand.Intn(len(phrases))

	return phrases[index]
}
